services:
  - type: web
    name: smart-blood-donation-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: roshankulkarni122@gmail.com
      - key: ADMIN_PASSWORD
        value: Roshan@2007
      - key: CLIENT_URL
        value: https://smart-blood-donation-system.onrender.com,http://localhost:5173
      - key: DB_NAME
        value: smart-blood-donation
      - key: MONGO_URI
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false

  - type: static
    name: smart-blood-donation-system
    rootDir: client
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://smart-blood-donation-api.onrender.com/api
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
